### ISSUE TITLE
Build a valid gvar for Texturina

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/fontmake-rs#245]
Compile Texturina with https://github.com/googlefonts/fontmake-rs/pull/236 and https://github.com/googlefonts/fontations/pull/351 in place, e.g. `cargo run -p fontc -- --source smoke_test/build/texturina/sources/Texturina.glyphs`

Ttx gvar:

```shell
$ ttx -o - -t gvar build/font.ttf
# prints some tuple's then boom
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "venv/lib/python3.10/site-packages/fontTools/ttx.py", line 405, in main
    process(jobs, options)
  File "venv/lib/python3.10/site-packages/fontTools/ttx.py", line 387, in process
    action(input, output, options)
  File "venv/lib/python3.10/site-packages/fontTools/misc/loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "venv/lib/python3.10/site-packages/fontTools/ttx.py", line 278, in ttDump
    ttf.saveXML(output,
  File "venv/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 241, in saveXML
    self._saveXML(writer, **kwargs)
  File "venv/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 296, in _saveXML
    self._tableToXML(tableWriter, tag, splitGlyphs=splitGlyphs)
  File "venv/lib/python3.10/site-packages/fontTools/ttLib/ttFont.py", line 327, in _tableToXML
    table.toXML(writer, self)
  File "venv/lib/python3.10/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 190, in toXML
    variations = self.variations.get(glyphName)
  File "/usr/lib/python3.10/_collections_abc.py", line 824, in get
    return self[key]
  File "venv/lib/python3.10/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 49, in __getitem__
    v = v()
  File "venv/lib/python3.10/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 122, in decompileVarGlyph
    return decompileGlyph_(numPointsInGlyph, sharedCoords, axisTags, gvarData)
  File "venv/lib/python3.10/site-packages/fontTools/ttLib/tables/_g_v_a_r.py", line 254, in decompileGlyph_
    return tv.decompileTupleVariationStore(
  File "venv/lib/python3.10/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 707, in decompileTupleVariationStore
    result.append(decompileTupleVariation_(
  File "venv/lib/python3.10/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 751, in decompileTupleVariation_
    deltas_x, pos = TupleVariation.decompileDeltas_(
  File "venv/lib/python3.10/site-packages/fontTools/ttLib/tables/TupleVariation.py", line 474, in decompileDeltas_
    assert len(result) == numDeltas
AssertionError
```

Make it happy.

**Comment by rsheeter** [comment]
Reproduces for just A, `cargo run -p fontc -- --source smoke_test/build/texturina/sources/Texturina.glyphs --glyph-name-filter ^A$`; ttx resuting font kerplodes.

**Comment by rsheeter** [comment]
I believe the fixes enumerated in https://github.com/googlefonts/fontations/pull/352 will help considerably or even fix; without those fixes round tripping the gvar data for Texturina's A fails.
